USE [HITRUST]
GO

/****** Object:  Table [dbo].[MXFUNDTB]    Script Date: 12/5/2026 5:42:05 pm ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MXFUNDTB](
	[FUNDKEY] [int] NOT NULL,
	[FUNDGROUPKEY] [int] NOT NULL,
	[FUNDSTATUSKEY] [int] NOT NULL,
	[PROFILEKEY] [int] NOT NULL,
	[OPENDATE] [datetime] NULL,
	[CLOSEDATE] [datetime] NULL,
	[CERTIFICATED] [bit] NOT NULL,
	[FUNDCODE] [char](10) NOT NULL,
	[DESCID] [int] NOT NULL,
	[UNITDECNO] [int] NULL,
	[NODEC] [int] NULL,
	[PAYFREQUENCY] [int] NULL,
	[SALESETTLEDAYS] [int] NULL,
	[REDSETTLEDAYS] [int] NULL,
	[DAYSNOTICE] [int] NULL,
	[MAXINISSUE] [float] NULL,
	[MGTFEEFREQ] [int] NULL,
	[MGTFEELVL] [int] NOT NULL,
	[CURRENCY] [int] NOT NULL,
	[SALEROUNDMETHOD] [int] NOT NULL,
	[DOMICILE] [int] NULL,
	[PRICEFREQ] [int] NULL,
	[FINYEAREND] [char](10) NULL,
	[STOCKX] [nchar](15) NULL,
	[BEARERSHARE] [bit] NOT NULL,
	[EXTSOURCE] [int] NULL,
	[STARTDATE] [datetime] NULL,
	[ENDDATE] [datetime] NULL,
	[MAINTUSER] [int] NOT NULL,
	[MAINTDATE] [datetime] NULL,
	[INCOMECALCMETHOD] [int] NULL,
	[DEFERREDPRICING] [bit] NOT NULL,
	[REDROUNDMETHOD] [int] NOT NULL,
	[PERFFEEFREQ] [int] NULL,
	[UNITCLASSINCOME] [bit] NOT NULL,
	[VALPRICETYPE] [int] NULL,
	[ISCASHTRUST] [bit] NOT NULL,
	[COMPANYKEY] [int] NOT NULL,
	[INCOMEMANAGEFEE] [numeric](38, 15) NULL,
	[DEDUCTINCOMEFEE] [bit] NOT NULL,
	[ACCRUALROUNDMETHOD] [int] NULL,
	[ACCRUALDECNO] [int] NULL,
	[MIDPRICEROUNDMETHOD] [int] NULL,
	[MINIMUMAGE] [int] NULL,
	[MANAGERBOXED] [bit] NOT NULL,
	[MANBOXMAXUNITS] [numeric](38, 15) NULL,
	[MANBOXPERCENTMAX] [numeric](38, 15) NULL,
	[MANBOXMAXAMOUNT] [numeric](38, 15) NULL,
	[FXRATETYPE] [int] NOT NULL,
	[EXTERNALID] [char](20) NULL,
	[AUSTAX] [bit] NOT NULL,
	[AUSGST] [bit] NOT NULL,
	[ABN] [char](15) NULL,
	[ADRCTFXRATE] [bit] NOT NULL,
	[AADRCTFXRATEOVR] [bit] NOT NULL,
	[ADRCTFXRATEOVR] [bit] NOT NULL,
	[INSURANCEALLOWED] [bit] NOT NULL,
	[INSUREMAXFACTOR] [float] NULL,
	[INSURECALMETHOD] [int] NULL,
	[INSUREPRICETYPE] [int] NULL,
	[INSUREMAXAMTCODE] [int] NULL,
	[INSURERATECODE] [int] NULL,
	[FUNDTYPEKEY] [int] NOT NULL,
	[FUNDFEEGROUP] [int] NULL,
	[UNITDEALSFXRATE] [int] NULL,
	[TAXLEGISLATION] [int] NULL,
	[INVESTMENTCLASSKEY] [int] NULL,
	[bonusunitspricetype] [int] NULL,
	[multipledistmethods] [int] NOT NULL,
	[EFFDATETRADECOUNTRY] [int] NULL,
	[EFFDATEFUNDCCYCOUNTRY] [int] NULL,
	[SETTLEDUETRADECOUNTRY] [int] NULL,
	[SETTLEDUEFUNDCCYCOUNTRY] [int] NULL,
	[ISDEFRECEIPTBANKACC] [bit] NOT NULL,
	[ISOVERRIDEDATETREATMENT] [bit] NOT NULL,
	[portfoliocode] [char](6) NULL,
	[COOLINGOFFRULEKEY] [int] NULL,
	[PREFCOMMFLAGTYPEKEY] [int] NULL,
	[ANNREPELECTTYPEKEY] [int] NULL,
	[ANNREPCOMMFLAGTYPEKEY] [int] NULL,
	[SIEFFDATEFROMSOSETTLEDUE] [bit] NOT NULL,
	[EFFDATECALENDARTYPE] [int] NULL,
	[SETTLEDUECALENDARTYPE] [int] NULL,
	[ISCORPORATETRUST] [bit] NOT NULL,
	[MGTFEERATE] [float] NULL,
	[ENTITYTYPEKEY] [int] NULL,
	[REGNO] [char](20) NULL,
	[ASSETSINCOMECOUNTRYKEY] [int] NULL,
	[ISIN] [char](12) NULL,
	[APPLYDAYSNOTICEONTRADINGDAYS] [bit] NOT NULL,
	[CUTOFFDATECOUNTRY] [int] NULL,
	[ADMINISTRATIONCOUNTRY] [int] NULL,
	[BILLERCODE] [varchar](6) NULL,
	[ATTRIBUTIONSTARTDATE] [datetime] NULL,
	[ATTRIBUTIONENDDATE] [datetime] NULL,
	[FUNDCATEGORY] [int] NULL,
	[PERFCALCROUNDMETHOD] [int] NULL,
	[PERFCALCSTARTMONTH] [int] NULL,
	[NODECPERFCALC] [int] NULL,
	[TAXIDKEY] [int] NULL,
	[TAXIDSUBTYPE] [int] NULL,
	[WHTONFUNDPAYMENT] [bit] NOT NULL,
	[WHTTREATMENTKEY] [int] NULL,
 CONSTRAINT [PK_MXFUNDTB] PRIMARY KEY CLUSTERED 
(
	[FUNDKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MXFUNDTB] ADD  DEFAULT (0) FOR [AUSTAX]
GO

ALTER TABLE [dbo].[MXFUNDTB] ADD  DEFAULT (0) FOR [AUSGST]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH CHECK ADD  CONSTRAINT [FK_FUND_ANNREPCOMMFLAGTYPE] FOREIGN KEY([ANNREPCOMMFLAGTYPEKEY])
REFERENCES [dbo].[MXCOMMFLAGTYPETB] ([COMMFLAGTYPEKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_FUND_ANNREPCOMMFLAGTYPE]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH CHECK ADD  CONSTRAINT [FK_FUND_ANNREPELECTTYPE] FOREIGN KEY([ANNREPELECTTYPEKEY])
REFERENCES [dbo].[MXANNREPELECTTYPETB] ([ANNREPELECTTYPEKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_FUND_ANNREPELECTTYPE]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH CHECK ADD  CONSTRAINT [FK_FUND_COUNTRY_ASSETSINCOME] FOREIGN KEY([ASSETSINCOMECOUNTRYKEY])
REFERENCES [dbo].[MXCOUNTRYTB] ([COUNTRYKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_FUND_COUNTRY_ASSETSINCOME]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH CHECK ADD  CONSTRAINT [FK_FUND_ENTITYTYPE] FOREIGN KEY([ENTITYTYPEKEY])
REFERENCES [dbo].[MXENTITYTYPETB] ([ENTITYTYPEKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_FUND_ENTITYTYPE]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH CHECK ADD  CONSTRAINT [FK_FUND_FUNDCATEGORY] FOREIGN KEY([FUNDCATEGORY])
REFERENCES [dbo].[MXFUNDCATEGORYTB] ([FUNDCATEGORYKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_FUND_FUNDCATEGORY]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH CHECK ADD  CONSTRAINT [FK_FUND_PREFCOMMFLAGTYPE] FOREIGN KEY([PREFCOMMFLAGTYPEKEY])
REFERENCES [dbo].[MXCOMMFLAGTYPETB] ([COMMFLAGTYPEKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_FUND_PREFCOMMFLAGTYPE]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH CHECK ADD  CONSTRAINT [FK_FUND_TAXID] FOREIGN KEY([TAXIDKEY])
REFERENCES [dbo].[MXTAXIDTB] ([TAXIDKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_FUND_TAXID]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH NOCHECK ADD  CONSTRAINT [FK_FUNDCLIENT] FOREIGN KEY([PROFILEKEY])
REFERENCES [dbo].[MXPROFILETB] ([PROFILEKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_FUNDCLIENT]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH NOCHECK ADD  CONSTRAINT [FK_FUNDFUNDGROUP] FOREIGN KEY([FUNDGROUPKEY])
REFERENCES [dbo].[MXFUNDGROUPTB] ([FUNDGROUPKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_FUNDFUNDGROUP]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH NOCHECK ADD  CONSTRAINT [FK_FUNDSTATUSFUND] FOREIGN KEY([FUNDSTATUSKEY])
REFERENCES [dbo].[MXFUNDSTATUSTB] ([FUNDSTATUSKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_FUNDSTATUSFUND]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH CHECK ADD  CONSTRAINT [FK_FUNDTB_FUNDTYPETB] FOREIGN KEY([FUNDTYPEKEY])
REFERENCES [dbo].[MXFUNDTYPETB] ([FUNDTYPEKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_FUNDTB_FUNDTYPETB]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH NOCHECK ADD  CONSTRAINT [FK_FUNDTB_INVCLSSTB] FOREIGN KEY([INVESTMENTCLASSKEY])
REFERENCES [dbo].[MXINVESTMENTCLASSTB] ([INVESTMENTCLASSKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_FUNDTB_INVCLSSTB]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH CHECK ADD  CONSTRAINT [FK_MXFUNDTB_ADMINCOUNTRY] FOREIGN KEY([ADMINISTRATIONCOUNTRY])
REFERENCES [dbo].[MXCOUNTRYTB] ([COUNTRYKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_MXFUNDTB_ADMINCOUNTRY]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH NOCHECK ADD  CONSTRAINT [FK_MXFUNDTB_COOLINGOFFRULETB] FOREIGN KEY([COOLINGOFFRULEKEY])
REFERENCES [dbo].[MXCOOLINGOFFRULETB] ([COOLINGOFFRULEKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_MXFUNDTB_COOLINGOFFRULETB]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH CHECK ADD  CONSTRAINT [FK_MXFUNDTB_CUTOFFDATECOUNTRY] FOREIGN KEY([CUTOFFDATECOUNTRY])
REFERENCES [dbo].[MXCOUNTRYTB] ([COUNTRYKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_MXFUNDTB_CUTOFFDATECOUNTRY]
GO

ALTER TABLE [dbo].[MXFUNDTB]  WITH NOCHECK ADD  CONSTRAINT [FK_MXFUNDTB_MXCOMPANYTB] FOREIGN KEY([COMPANYKEY])
REFERENCES [dbo].[MXCOMPANYTB] ([COMPANYKEY])
GO

ALTER TABLE [dbo].[MXFUNDTB] CHECK CONSTRAINT [FK_MXFUNDTB_MXCOMPANYTB]
GO


